version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.2
    container_name: socialNetwork-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - socialNetwork-network
#    command: >
#      bash -c '
#      if ! elasticsearch-plugin list | grep -q "analysis-icu"; then
#        elasticsearch-plugin install analysis-icu
#      else
#        tail -f /dev/null &
#      fi'
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:8.15.2
    container_name: socialNetwork-logstash
    ports:
      - "5044:5044"
    volumes:
      - "./logstash-ingest-data/:/usr/share/logstash/ingest_data/"
      - "./logstash-config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
    restart: always
    networks:
      - socialNetwork-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.2
    container_name: socialNetwork-kibana
    ports:
      - "5601:5601"
    networks:
      - socialNetwork-network
    restart: always

  minio:
    image: quay.io/minio/minio:latest
    container_name: socialNetwork-minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=ROOTUSER
      - MINIO_ROOT_PASSWORD=CHANGEME123
    command: server /data --console-address ":9090"
    volumes:
      - minio-data:/data
    restart: always
    networks:
      - socialNetwork-network

networks:
  ddmdemo-network:
    name: socialNetwork-network

volumes:
  minio-data:
